# Generated by Django 4.0.3 on 2022-07-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0002_empolyee_date_of_birth'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empolyee',
            new_name='Employee',
        ),
    ]
