# Generated by Django 4.0.6 on 2022-07-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_employee_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='profile_picture',
        ),
    ]
